"use client";

import { BiSearch } from "react-icons/bi";

const Search = () => {
  return (
    <div
      className="
            border-[1px]
            w-3/5
            max-w-[850px]
            md:min-w-[700px]
            min-w-[350px]
            h-[65px]
            rounded-full
            shadow-md
            hover:shadow-md
            transition
            cursor-pointer
        "
    >
      <div
        className="
                h-full
                flex
                flex-row
                items-center
                justify-between
            "
      >
        <div
          className="
                h-full
                text-sm
                pl-3
                font-semibold
                grow
                rounded-full
                md:hover:bg-neutral-200
            "
        >
          <div
            className="
              h-full
              p-3
              flex
              flex-col
            "
          >
            <div
              className="
                text-xs
              "
            >
              여행지
            </div>
            <input
              type="text"
              placeholder="여행지 검색"
              className="
                h-full
                placeholder-neutral-500
                font-normal
                bg-white
                bg-opacity-0
                border-none
                focus:outline-none
              "
            />
          </div>
        </div>
        <div
          className="
                hidden 
                md:block
                pl-3
                h-full
                text-sm
                font-semibold
                grow
                rounded-full
                hover:bg-neutral-200
            "
        >
          <div
            className="
              h-full
              p-3
              flex
              flex-col
            "
          >
            <div
              className="
                text-xs
                font-bold
              "
            >
              체크인
            </div>
            <div
              className="
                h-full
                text-sm
                text-neutral-500
                font-normal
                bg-white
                bg-opacity-0
                border-none
                focus:outline-none
              "
            >
              날짜 추가
            </div>
          </div>
        </div>
        <div
          className="
                hidden 
                md:block
                pl-3
                h-full
                text-sm
                font-semibold
                grow
                rounded-full
                hover:bg-neutral-200
            "
        >
          <div
            className="
              h-full
              p-3
              flex
              flex-col
            "
          >
            <div
              className="
                text-xs
                font-bold
              "
            >
              체크아웃
            </div>
            <div
              className="
                h-full
                text-sm
                text-neutral-500
                font-normal
                bg-white
                bg-opacity-0
                border-none
                focus:outline-none
              "
            >
              날짜 추가
            </div>
          </div>
        </div>
        <div
          className="
                pr-3
                h-full
                flex
                flex-row
                md:justify-between
                justify-center
                items-center
                gap-3
                md:grow
                rounded-full
                md:hover:bg-neutral-200
            "
        >
          <div
            className="
                pl-3
                hidden 
                md:block
                h-full
                w-full
                text-sm
                font-semibold
            "
          >
            <div
              className="
              h-full
              p-3
              flex
              flex-col
              
            "
            >
              <div
                className="
                text-xs
                font-bold
              "
              >
                여행자
              </div>
              <div
                className="
                h-full
                text-sm
                text-neutral-500
                font-normal
                bg-white
                bg-opacity-0
                border-none
                focus:outline-none
              "
              >
                게스트 추가
              </div>
            </div>
          </div>
          <div
            className="
                    p-2
                    bg-primary
                    rounded-full
                    text-white
                "
          >
            <BiSearch size={18} />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Search;
